spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

      
logging:
  config: classpath:logback-spring.xml
  path: /var/log/raisin
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
